apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: kwt-prod
  labels:
    app.kubernetes.io/name: front
    app.kubernetes.io/instance: front-prod
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: k8s-kwt
    app.kubernetes.io/managed-by: kubectl
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: front
      app.kubernetes.io/instance: front-prod
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: k8s-kwt
      env: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front
        app.kubernetes.io/instance: front-prod
        app.kubernetes.io/version: v1.0.0
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: k8s-kwt
        app.kubernetes.io/managed-by: kubectl
        env: prod
    spec:
      containers:
        - name: front
          image: wondookong/kwt-production-front:latest
          ports:
          - containerPort: 3000
#          startupProbe:
#            httpGet:
#              path: "/startup"
#              port: 3000
#            periodSeconds: 5
#            failureThreshold: 36
#          readinessProbe:
#            httpGet:
#              path: "/readiness"
#              port: 3000
#            periodSeconds: 10
#            failureThreshold: 3
#          livenessProbe:
#            httpGet:
#              path: "/liveness"
#              port: 3000
#            periodSeconds: 10
#            failureThreshold: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64