apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: kwt-prod
spec:
  selector:
    project: kwt
    app: front
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP